name: psyplot_docs
channels:
    - local
    - psyplot/label/__CURRENTBRANCH__
    - psyplot/label/master
    - conda-forge
dependencies:
    - python=3.8
    - dask
    - netCDF4
    - seaborn
    - sphinx
    - sphinx_rtd_theme
    - psy-simple
    - psyplot-gui
    - autodocsumm
    - pip
